# Generated by Django 5.2.16 on 2026-07-09 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_alter_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='paid_by_friend',
            field=models.ForeignKey(blank=True, help_text='If set, this friend paid for the expense instead of the owner.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses_paid', to='ledger.friend'),
        ),
        migrations.AddField(
            model_name='payment',
            name='direction',
            field=models.CharField(choices=[('received', 'Received from friend'), ('sent', 'Sent to friend')], db_index=True, default='received', max_length=20),
        ),
        migrations.AddField(
            model_name='receivable',
            name='direction',
            field=models.CharField(choices=[('owed_to_me', 'Owed to me'), ('owed_by_me', 'Owed by me')], db_index=True, default='owed_to_me', max_length=20),
        ),
    ]
